{{- if and .Values.configmap.enabled .Values.configmap.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
data:
  {{- with .Values.configmap.data }}
  {{ toYaml . | indent 2 }}
  {{- end }}
{{- end }}
