apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "demo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "demo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: tcp-jmx
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.hostNetwork }}
          hostNetwork: {{ .Values.hostNetwork }}
        {{ end }}
        {{- with .Values.dnsPolicy }}
          dnsPolicy: {{ .Values.dnsPolicy }}
        {{ end }}
          env:
            - name: PROFILE
              value: {{ .Values.profile }}
            - name: NAMESPACE
              value: {{ .Values.namespace }}
            - name: VERSION
              value: {{ .Values.image.tag }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rdssecrets
                  key: mysql_password
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rdssecrets
                  key: mysql_user
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: rdssecrets
                  key: mysql_url
        {{- with .Values.env }}
          {{ toYaml . | indent 12 }}
        {{- end }}
        {{ if or .Values.configmap.enabled .Values.secret.enabled }}
          envFrom:
        {{ end }}
        {{ if .Values.configmap.enabled }}
            - configMapRef:
                name: {{ include "demo.fullname" . }}
        {{ end }}
        {{ if .Values.secret.enabled }}
            - secretRef:
                name: {{ include "demo.fullname" . }}
        {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
