{{- if and .Values.secret.enabled .Values.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secret.data }}
  {{ toYaml . | indent 2 }}
  {{- end }}
{{- end }}
