name: Build-Cron

on:
  schedule:
#    - cron: "* * * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Bump
        run: |
          bash ./build.sh bump
          
      - name: Commit & Push
        uses: timzu/act-build@master
        with:
          args: --commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE_PATH: ./build/commit_message.txt
